config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  ##resources :tasks

  #delte
  delete "tasks/:id", to: "tasks#destroy", as: :destroy_tasks

  #update get the form and edit it
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_tasks
  patch "tasks/:id", to: "tasks#update", as: :task

  #create new tasks (show form and save)
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  #show all tasks (root) and details
  root to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: :detail

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to root_path
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <p><%= f.label :title %>
  <%= f.text_field :title %><br></p>
  <p><%= f.label :details %>
  <%= f.text_field :details %><br></p>
  <p><%= f.label :completed %>
  <%= f.check_box :completed %><br></p>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
<% @tasks.each do |task| %>
  <li><%= link_to task.title, detail_path(task) %>
    | <%= link_to "Edit", edit_tasks_path(task.id) %>
    | <%= link_to "Delete", destroy_tasks_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
<% end %>
</ul>
<p>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <p><%= f.label :title %>
  <%= f.text_field :title %><br></p>
  <p><%= f.label :details %>
  <%= f.text_field :details %><br></p>
  <p><%= f.label :completed %>
  <%= f.check_box :completed %><br></p>
  <%= f.submit %>
<% end %>
<p>

<%= link_to "Back to list", root_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Back to list", root_path %>